[package]
name = "dex"
version = "0.1.0"
edition = "2018"
description = "Cross-platform Pokédex."
authors = ["Teddy Byron <ted@tedbyron.com>"]
repository = "https://github.com/tedbyron/dex"
documentation = "https://github.com/tedbyron/dex"
readme = "README.md"
license = "MIT OR Apache-2.0"
resolver = "2"

[dependencies]
getrandom = { version = "0.2.3", features = ["js"] }
rand = "0.8.4"
reqwest = { version = "0.11.6", features = ["json"] }
serde = { version = "1.0.130", features = ["derive"] }
pokeapi = { path = "./pokeapi-rs/" }

[dependencies.iced]
features = ["image", "debug", "tokio"]
git = "https://github.com/iced-rs/iced"

[profile.dev]
debug = 0

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
